---
title: "Low level vs high level visual prediction processing"
author: "Max Van Migem"
date: "2025-08-20"
---

```{r packages}
library(car)
library(pbkrtest)
library(lmerTest)
library(lme4)
library(optimx)
library(performance)
library(emmeans)
# library(brms)
# library(rstan)

```
## load data

```{r data}
# df <- read.csv('C:/Users/mvmigem/Documents/data/project_2/compiled_data/behaviour_acc.csv')
df <- read.csv('C:/Users/mvmigem/Documents/data/project_2/compiled_data/behaviour_dprime.csv')
# df <- read.csv('C:/Users/mvmigem/Documents/data/project_2/compiled_data/behaviour_rt.csv')
# df <- read.csv('C:/Users/mvmigem/Documents/data/project_2/compiled_data/behaviour_acc_trials.csv')
# df <- read.csv('C:/Users/mvmigem/Documents/data/project_2/compiled_data/behaviour_rt_trial.csv')

```
```{r data}
df$participant <- as.factor(df$participant)
df$feature <- as.factor(df$feature)
df$attended_feature <- as.factor(df$attended_feature)
df$unattended_feature <- as.factor(df$unattended_feature)


options(contrasts = c("contr.sum", "contr.poly"))

df_angle <- subset(df, feature == 'angle')
df_rotation <- subset(df, feature == 'rotation')
df_att_reg <- subset(df_angle, attended_feature == 'regular')
df_att_odd <- subset(df_angle, attended_feature == 'odd')

df_att_reg_y <- subset(df_att_reg, unattended_feature == 'odd')
df_att_odd_y <- subset(df_att_odd, unattended_feature == 'odd')

df_att_odd_x <- subset(df_att_reg, unattended_feature == 'odd')
df_att_reg_x <- subset(df_att_reg, unattended_feature == 'regular')

df_unat_reg <- subset(df_rotation, unattended_feature == 'regular')
df_unat_odd <- subset(df_rotation, unattended_feature == 'odd')

```

## the behaviour model

# acc
```{r}

f1 <- accuracy ~ 1 + feature + attended_feature + unattended_feature + 
                feature*attended_feature*unattended_feature + 
                (1 + feature + attended_feature +unattended_feature | participant)

f2 <- accuracy ~ 1 + feature + attended_feature + unattended_feature + 
                feature*attended_feature*unattended_feature + 
                (1 | participant) # This one fit better

fit.behaviour_acc <-  lmer(f1, data = df, control = lmerControl(optimizer ='optimx', optCtrl=list(method='L-BFGS-B')))
fit.behaviour_acc_2 <-  lmer(f2, data = df, control = lmerControl(optimizer ='optimx', optCtrl=list(method='L-BFGS-B')))


f1 <- acc_01 ~ 1 + feature + attended_feature + unattended_feature + 
                feature*attended_feature*unattended_feature + 
                (1 + feature + attended_feature +unattended_feature | participant)

f2 <- acc_01 ~ 1 + feature + attended_feature + unattended_feature + 
                feature*attended_feature*unattended_feature + 
                (1 + feature + attended_feature | participant) # better


fit.behaviour_acc <-  glmer(f1, data = df, family = binomial, control = glmerControl(optimizer ='bobyqa', optCtrl=list(maxfun = 1e5)))
fit.behaviour_acc_2 <-  glmer(f2, data = df, family = binomial, control = glmerControl(optimizer ='bobyqa', optCtrl=list(maxfun = 1e5)))

confint(fit.behaviour_acc_2, method ="Wald",nsim = 1000)
summary(fit.behaviour_acc)
summary(fit.behaviour_acc_2)
contrasts(df$feature)
contrasts(df$attended_feature)
contrasts(df$unattended_feature)

df_check = subset(df, attended_feature == 'regular')
df_chock = subset(df, attended_feature == 'odd') 

mean(df_check$accuracy, na.rm = TRUE)
sd(df_check$accuracy, na.rm = TRUE)
mean(df_chock$accuracy, na.rm = TRUE)
sd(df_chock$accuracy, na.rm = TRUE)

confint(emmeans(fit.behaviour_acc_2, pairwise ~ attended_feature | feature))
emmeans(fit.behaviour_acc_2, pairwise ~ attended_feature | feature)
```
# dprime
```{r}
f1 <- dprime ~ 1 + feature + unattended_feature + 
                feature*unattended_feature + 
                (1 + feature  + unattended_feature | participant)

f2 <- dprime ~ 1 + feature + unattended_feature + 
                feature*unattended_feature + 
                (1 + feature   | participant) # better afbootstrap

f1 <- beta ~ 1 + feature + unattended_feature + 
                feature*unattended_feature + 
                (1 + feature  + unattended_feature | participant)

f2 <- beta ~ 1 + feature + unattended_feature + 
                feature*unattended_feature + 
                (unattended_feature | participant)

f1 <- c ~ 1 + feature + unattended_feature + 
                feature*unattended_feature + 
                (1 + feature  + unattended_feature | participant)

f2 <- c ~ 1 + feature + unattended_feature + 
                feature*unattended_feature + 
                (1| participant)


fit.behaviour_acc <-  lmer(f1, data = df, control = lmerControl(optimizer ='optimx', optCtrl=list(method='L-BFGS-B')))
fit.behaviour_acc_2 <-  lmer(f2, data = df, control = lmerControl(optimizer ='optimx', optCtrl=list(method='L-BFGS-B')))

confint(fit.behaviour_acc, method ="boot",nsim = 1000)
summary(fit.behaviour_acc)
summary(fit.behaviour_acc_2)
contrasts(df$feature)
contrasts(df$attended_feature)
contrasts(df$unattended_feature)

mean(df_regular$beta, na.rm = TRUE)
sd(df_regular$beta, na.rm = TRUE)
mean(df_odd$beta, na.rm = TRUE)
sd(df_odd$beta, na.rm = TRUE)

emmeans(fit.behaviour_acc_2, pairwise ~ unattended_feature | attended_feature)
emmeans(fit.behaviour_acc, ~ unattended_feature + feature)
emm <- emmeans(fit.behaviour_acc_2, ~ unattended_feature + feature)

# Test whether each cell mean differs from zero
test(emm, null = 0)
```
# rt
```{r}

f1 <- rt ~ 1 + feature + attended_feature + unattended_feature + 
        feature*attended_feature*unattended_feature + 
        (1 + feature + attended_feature | participant) # dropped unattended_feature out of random eff because convergence

f2 <- rt ~ 1 + feature + attended_feature + unattended_feature + 
        feature*attended_feature*unattended_feature + 
        (1 + feature + attended_feature + unattended_feature | participant) # for trial level analyses


fit.behaviour_rt <-  lmer(f1, data = df, control = lmerControl(optimizer = c("Nelder_Mead"), optCtrl=list(maxfun=2e6)))
fit.behaviour_rt2 <-  glmer(f2, family = Gamma(link = "log"), data = df, control = glmerControl(optimizer = c("bobyqa"), optCtrl=list(maxfun=2e6)))

confint(fit.behaviour_rt2, method ="Wald")
summary(fit.behaviour_rt)
summary(fit.behaviour_rt2)
contrasts(df$feature)
contrasts(df$attended_feature)
contrasts(df$unattended_feature)
emmeans(fit.behaviour_rt2, pairwise ~ attended_feature | feature)
confint(emmeans(fit.behaviour_rt2, pairwise ~ attended_feature*unattended_feature | feature))

median(df_rotation$rt, na.rm = TRUE)
sd(df_rotation$rt, na.rm = TRUE)
mean(df_angle$rt, na.rm = TRUE)
sd(df_angle$rt, na.rm = TRUE)

median(df_att_odd_x$rt, na.rm = TRUE)
IQR(df_att_odd_x$rt, na.rm = TRUE)
median(df_att_reg_x$rt, na.rm = TRUE)
IQR(df_att_reg_x$rt, na.rm = TRUE)

```
```{r}
anova(fit.behaviour_acc,fit.behaviour_acc_2)
summary(fit.behaviour_acc)
summary(fit.behaviour_acc_2)
plot(fit.behaviour_acc_2)
qqnorm(residuals(fit.behaviour_acc_2))
bootstrap|> tidy()
bootstrap <- PBmodcomp(fit.behaviour_acc,fit.behaviour_acc_2,nsim=1000)
check_model(fit.behaviour_acc)
check_model(fit.behaviour_acc_2)
check_model(fit.behaviour_rt2)

summary(bootstrap)

```